# Generated by Django 3.2 on 2021-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20210709_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='img',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
