# Generated by Django 3.2 on 2021-07-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_address_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='img',
        ),
    ]
